name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths: ["contract-utils/**", ".github/workflows/cli.yaml"]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    env:
      TEST_RPC_URL: ${{secrets.TEST_RPC_URL}}
      TEST_MNEMONIC: ${{secrets.TEST_MNEMONIC}}
      TEST_CONTRACT_ADDRESS: ${{secrets.TEST_CONTRACT_ADDRESS}}
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-09-19
          override: true
          components: rustfmt, clippy
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          cd contract-utils
          rustc --version
          cargo build -vv
      - name: Run tests
        run: |
          cd contract-utils
          cargo test  -- --nocapture --test-threads 1
